import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Its Just Sex - Free Hookup Site for Casual Encounters",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const clickId = cookieStore.get("clickid")?.value || "";
  const safe = (v: string) => v.replace(/"/g, '\\"');
  return (
    <html lang="en">
      <head>
        <Script
          id="click-id-inline"
          strategy="beforeInteractive"
        >
          {`window.TRACKING_CLICKID = "${safe(clickId)}";`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
